### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mikeatlas** [chick307/adler32cs.js#3]
Hi - any chance you can add a license to your code? 

https://github.com/pivotal/LicenseFinder#a-plea-to-package-authors-and-maintainers

GitHub also now offers a setting per repo to setup the License property

**Comment by ujh** [comment]
Yes, that would be really cool. It's a dependency of `jspdf-yworks` and sadly that will prevent us from using it.

**Comment by ujh** [comment]
👍 Thank you!
