### ISSUE TITLE
Undefined ls-remote when install wtih on another project on Npm

### ISSUE THREAD

**Issue by emehmet** [chick307/adler32cs.js#7]
Hi,
I use tableexport.jquery.plugin a node project on windows 10 with npm. When I try to install on this project on npm I get this error.

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/chick307/adler32cs.js.git

Can you help for this?

**Comment by chick307** [comment]
This is not a problem with this repository.
